### PR TITLE
Reintroduce time unit for performance benchmarking

### LINKED ISSUE #701: Achilles benchmarking results strip time-unit from execution duration (and mixing units)
**Describe the bug**
When extracting analysis execution duration, Achilles result benchmark strips the unit and only stores the value in the database. 
The log has a formatted execution duration, e.g. automatically displaying in seconds, minutes, hours whichever is more applicable.
This information is stripped, so there is no way of knowing what the value is. See screenshot below. 
To confirm: all values are between 0-60, so definitely not all seconds.
image

Note that in older Achilles versions the unit WAS kept in the database. I have narrowed down the issue being introduced in December 2021, in a series of commits ending with: https://github.com/OHDSI/Achilles/commit/d81fae98d83f623ab1e901a56827cb96a67cc75f

**Solution direction**
There are two possible solutions:
* Convert all execution durations to seconds
* Keep the unit. The stratum_1 field is of type varchar, so this is possible.

https://github.com/OHDSI/Achilles/blob/a9144b2f3119055b76dfe8e9d798654558127fe3/R/Achilles.R#L1072

### PR DESCRIPTION
**Pull request by MaximMoinat**
Fixes #701 and some refactoring. 
See in-line comments explaining the main changes.

### CODE REVIEW

File: R/Achilles.R [hunk 1]
```diff
@@ -1054,37 +1076,49 @@ optimizeAtlasCache <- function(connectionDetails,
...
-                                             "log_achilles.txt"), header = FALSE, sep = "\t",
-    stringsAsFactors = FALSE)
+.getAchillesResultBenchmark <- function(analysisId, logs) {
+  logs <- logs[logs$analysisId == analysisId, ]
+  if (nrow(logs) == 1) {
+    runTime <- strsplit(logs[1, ]$runTime, " ")[[1]]
+    runTimeValue <- round(as.numeric(runTime[1]), 2)
+    runTimeUnit <- runTime[2]
+    paste(runTimeValue, runTimeUnit)
+  } else {
```
Comment (MaximMoinat) [inline R/Achilles.R:1086]: This is the change fixing the issue

File: R/Achilles.R [hunk 2]
```diff
@@ -933,59 +933,81 @@ optimizeAtlasCache <- function(connectionDetails,
...
   })
 
   # obtain the analysis SQLs to union in the merge
   # ------------------------------------------------------------------
-
-  detailSqls <- lapply(resultsTable$analysisIds[resultsTable$analysisIds %in% analysisIds],
-                       function(analysisId) {
-    analysisSql <- SqlRender::render(sql = "select @castedNames from
+  if (!sqlOnly) {
+    logs <- .parseLogs(outputFolder)
```
Comment (MaximMoinat) [inline R/Achilles.R:956]: Read log file only once, instead of every time for each analysis id.

**Comment by MaximMoinat** [comment]
@fdefalco @AnthonyMolinaro Updated to convert runtime to seconds, please review.
